### ISSUE TITLE
Problem redirect to frontend

### ISSUE THREAD

**Issue by coachdesign** [Flagbit/Magento-ChangeAttributeSet#13] opened 2015-12-01 17:33 UTC
Hi, i have update to the last version of the module.
Now when i try to change attribute set and click on buttom "submit" redirect on 404 not found (frontend).

Admin url before submit:
http://www.mydomain.it/index.php/admin/catalog_product/index/key/a731c6282f871a8c5d73546c8e63660f/

Url after submit:
http://www.mydomain.it/index.php/admin/catalog_product/changeattributeset/key/33c7d3abb4975c4c9459c7fdbf3bcc13/_blcg_token_/blcg:76d8c1c44e737b6003bd7f8e648978a5/

**Comment by davidfuhr** [comment] 2015-12-01 19:59
Duplicate of #12

**Closed by davidfuhr** 2015-12-01 19:59 UTC

**Comment by coachdesign** [comment] 2015-12-02 07:17
Thanks, now return this error:
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction

**Comment by coachdesign** [comment] 2015-12-02 07:21
with reindex, solved...
